# Generated by Django 5.2.6 on 2025-09-06 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий')),
                ('lang', models.CharField(default='ru', max_length=8, verbose_name='Язык')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('inwork', 'В работе'), ('done', 'Завершена')], default='new', max_length=16, verbose_name='Статус')),
                ('utm_source', models.CharField(blank=True, max_length=64)),
                ('utm_medium', models.CharField(blank=True, max_length=64)),
                ('utm_campaign', models.CharField(blank=True, max_length=64)),
                ('consent', models.BooleanField(default=True, verbose_name='Согласие с политикой')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
