# Generated by Django 5.2.6 on 2025-09-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(default='Avto_Him_Zavod', max_length=120, verbose_name='Бренд')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Короткое описание')),
                ('phone_display', models.CharField(default='+996 XXX XX-XX-XX', max_length=32, verbose_name='Телефон (для показа)')),
                ('phone_e164', models.CharField(default='+996', max_length=32, verbose_name='Телефон в E.164')),
                ('whatsapp_link', models.URLField(blank=True, verbose_name='Ссылка WhatsApp')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Ссылка Telegram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('street_address', models.CharField(default='ул. Алматинская, 8', max_length=255, verbose_name='Адрес')),
                ('address_locality', models.CharField(default='Бишкек', max_length=120, verbose_name='Город')),
                ('address_region', models.CharField(default='Чуйская область', max_length=120, verbose_name='Регион')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Индекс')),
                ('address_country', models.CharField(default='KG', max_length=64, verbose_name='Страна (ISO2 или название)')),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('geo_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('hours_mon', models.CharField(default='09:00-18:00', max_length=50, verbose_name='Пн')),
                ('hours_tue', models.CharField(default='09:00-18:00', max_length=50, verbose_name='Вт')),
                ('hours_wed', models.CharField(default='09:00-18:00', max_length=50, verbose_name='Ср')),
                ('hours_thu', models.CharField(default='09:00-18:00', max_length=50, verbose_name='Чт')),
                ('hours_fri', models.CharField(default='09:00-18:00', max_length=50, verbose_name='Пт')),
                ('hours_sat', models.CharField(default='10:00-17:00', max_length=50, verbose_name='Сб')),
                ('hours_sun', models.CharField(default='closed', max_length=50, verbose_name='Вс')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
