# Generated by Django 5.2.6 on 2025-09-06 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Целое число 1–5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('google', 'Google'), ('2gis', '2ГИС'), ('instagram', 'Instagram'), ('manual', 'Ручной ввод')], default='manual', max_length=20, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='review',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL на Google/2ГИС/Instagram (если есть)', verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_published'], name='core_review_is_publ_f740cd_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='core_review_created_fff155_idx'),
        ),
    ]
