# Generated by Django 5.2.6 on 2025-09-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_brand_productcategory_product_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название филиала')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('phone_e164', models.CharField(blank=True, max_length=20, verbose_name='Телефон в E.164')),
                ('whatsapp_link', models.URLField(blank=True, verbose_name='WhatsApp ссылка')),
                ('street_address', models.CharField(max_length=180, verbose_name='Улица, дом')),
                ('address_locality', models.CharField(default='Бишкек', max_length=120, verbose_name='Город/район')),
                ('address_region', models.CharField(default='Чуйская область', max_length=120, verbose_name='Регион')),
                ('address_country', models.CharField(default='KG', max_length=2, verbose_name='Страна')),
                ('geo_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('geo_lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('hours_mon', models.CharField(blank=True, default='09:00–18:00', max_length=60, verbose_name='Пн–Пт')),
                ('hours_sat', models.CharField(blank=True, default='10:00–16:00', max_length=60, verbose_name='Сб')),
                ('hours_sun', models.CharField(blank=True, default='выходной', max_length=60, verbose_name='Вс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ('sort', 'name'),
            },
        ),
    ]
