# Generated by Django 5.2.6 on 2025-09-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_youtube_id',
            field=models.CharField(blank=True, help_text='ID видео с YouTube, например: dQw4w9WgXcQ из https://youtu.be/dQw4w9WgXcQ', max_length=50, verbose_name='YouTube ID главного видео'),
        ),
    ]
